services:
  - name: vozmulti-backend
    type: web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 8000
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/google-tts.json
    disk:
      name: projects-disk
      mountPath: ./projects
      sizeGB: 5
    autoDeploy: true
    # Añade tu archivo de credenciales de Google TTS como secreto en Render
    secrets:
      - name: google-tts.json
        file: google-tts.json

  - name: vozmulti-frontend
    type: web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run webui.py --server.port 10000 --server.address 0.0.0.0
    envVars:
      - key: API_URL
        # Cambia esto por la URL de tu backend una vez desplegado, por ejemplo:
        value: https://vozmulti-backend.onrender.com
    autoDeploy: true